using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Windows.Media.Imaging;

namespace MilovanaEosEditor;

/// <summary>
/// Step 6 of the tease workflow (EOS-Tease-Authoring-Guide.md §1, §5.1–5.2): build
/// <c>asset-map.json</c> by joining the editor-exported <c>tease.json</c> manifest to the local
/// source files. Gallery images are matched by <b>SHA-1</b> of their bytes (the manifest <c>hash</c>
/// field is SHA-1); audio/other files by <b>filename</b> (the <c>files</c> manifest is keyed by it).
/// Manifest <c>width</c>/<c>height</c> are unreliable, so true dimensions are read from the local
/// image. As a side effect it also seeds empty tag stubs into <c>asset-content.json</c> for any
/// newly-mapped images so only the new pictures need vision-tagging (step 7).
///
/// The map is fully <i>derived</i> from <c>tease.json</c> + disk, so a regenerate is deterministic:
/// re-running yields byte-identical output and seeds nothing new — i.e. the operation is idempotent.
/// </summary>
internal static class AssetMapGenerator
{
    // Shared by the whole tool so asset-map.json and asset-content.json serialize identically:
    // indented, camelCase keys (matching the hand-authored files), and the relaxed encoder so
    // apostrophes/parentheses in notes stay human-readable rather than \u-escaped.
    public static readonly JsonSerializerOptions WriteOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    public static readonly JsonSerializerOptions ReadOptions = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    private const string MapDescription =
        "Per-tease mapping from Milovana server asset IDs (uuid/image id, file name) to the local " +
        "source files under this folder. Milovana re-uploads and re-IDs assets per tease, so this " +
        "map is tease-local. Built by matching each local file's SHA-1 to the manifest 'hash' field " +
        "in tease.json (exact content match). Note: Milovana manifest width/height are unreliable " +
        "(some report 100x100); width/height here are the true local dimensions. " +
        "Generated by MilovanaEosEditor (--generate-map); do not hand-edit.";

    // Seeded into a freshly-created asset-content.json only (an existing file's own block is kept).
    private const string ContentDescription =
        "Vision-derived content tags per local image, keyed by <GalleryName>/<filename> (stable " +
        "local-content identity, independent of Milovana IDs). Used to select images matching a " +
        "script's subject + pace + exposure. explicitness and pace are TWO INDEPENDENT AXES: " +
        "explicitness = how much is shown (ordered: clothed < underwear < partial-nudity < nude < " +
        "explicit); pace = how energetic/fast the scene is (1-5, ignoring nudity). Tags are Claude's " +
        "visual judgement and should be user-verified. Join with asset-map.json on the filename key " +
        "to get the playable locator. See EOS-Tease-Authoring-Guide.md §5.3.";

    private const string ContentVocabularyJson = """
        {
          "subject": ["solo", "machine", "partner"],
          "explicitness": ["clothed", "underwear", "partial-nudity", "nude", "explicit"],
          "pace": "Energy/tempo of the scene only, independent of explicitness. 1 (still/sensual/posed) to 5 (frantic/hard). Anchored to BPM bands for matching to the metronome (1: <=40, 2: 40-70, 3: 70-110, 4: 110-150, 5: 150+).",
          "orientation": ["portrait", "landscape"]
        }
        """;

    /// <summary>
    /// Build <c>asset-map.json</c> (and seed <c>asset-content.json</c> stubs) for the tease folder.
    /// </summary>
    /// <param name="teaseDir">Folder containing <c>tease.json</c>, <c>Gallery/&lt;name&gt;/</c>, <c>Files/</c>.</param>
    public static GenerateResult Run(string teaseDir)
    {
        teaseDir = Path.GetFullPath(teaseDir);
        string teaseName = new DirectoryInfo(teaseDir).Name;
        string teaseJsonPath = Path.Combine(teaseDir, "tease.json");
        if (!File.Exists(teaseJsonPath))
            throw new FileNotFoundException($"No tease.json found in '{teaseDir}'.", teaseJsonPath);

        JsonNode manifest = JsonNode.Parse(File.ReadAllText(teaseJsonPath))
            ?? throw new InvalidDataException("tease.json did not parse to a JSON object.");

        var result = new GenerateResult { Tease = teaseName };

        var map = new AssetMap
        {
            Tease = teaseName,
            Description = MapDescription,
            HashAlgorithm = "sha1",
        };

        // ---- galleries: match manifest images to local files by SHA-1 within each gallery folder ----
        // Captures derived (gallery, filename) -> orientation so the content-stub seeding can prefill
        // the one tag axis we know reliably from dimensions.
        var seededOrientation = new Dictionary<(string Gallery, string File), string>();

        if (manifest["galleries"] is JsonObject galleries)
        {
            foreach ((string uuid, JsonNode? gNode) in galleries)
            {
                if (gNode is null) continue;
                string name = gNode["name"]?.GetValue<string>() ?? uuid;
                string folderRel = $"Gallery/{name}";
                string folderAbs = Path.Combine(teaseDir, "Gallery", name);

                Dictionary<string, LocalImage> localByHash = IndexLocalImages(folderAbs);
                var matchedHashes = new HashSet<string>();

                var mapGallery = new MapGallery { Uuid = uuid, LocalFolder = folderRel };

                foreach (JsonNode? imgNode in (JsonArray?)gNode["images"] ?? new JsonArray())
                {
                    if (imgNode is null) continue;
                    result.ManifestImages++;
                    long id = imgNode["id"]?.GetValue<long>() ?? 0;
                    long size = imgNode["size"]?.GetValue<long>() ?? 0;
                    string hash = (imgNode["hash"]?.GetValue<string>() ?? string.Empty).ToLowerInvariant();

                    if (localByHash.TryGetValue(hash, out LocalImage? local))
                    {
                        result.MatchedImages++;
                        matchedHashes.Add(hash);
                        mapGallery.Images[local.FileName] = new MapImage
                        {
                            Id = id,
                            Hash = hash,
                            Size = size,
                            Width = local.Width,
                            Height = local.Height,
                            Locator = $"gallery:{uuid}/{id}",
                        };
                        if (local.Width > 0 && local.Height > 0)
                            seededOrientation[(name, local.FileName)] =
                                local.Width < local.Height ? "portrait" : "landscape";
                    }
                    else
                    {
                        result.UnmatchedImages.Add(
                            $"gallery '{name}' ({uuid}) image id {id} hash {hash} - no local file");
                    }
                }

                foreach ((string hash, LocalImage local) in localByHash)
                {
                    if (!matchedHashes.Contains(hash))
                        result.UnusedLocalFiles.Add($"{folderRel}/{local.FileName} (hash {hash}) - not in manifest");
                }

                map.Galleries[name] = mapGallery;
                result.GalleriesCount++;
            }
        }

        // ---- files: match by filename (the manifest is keyed by it) ----
        if (manifest["files"] is JsonObject files)
        {
            foreach ((string fileName, JsonNode? fNode) in files)
            {
                if (fNode is null) continue;
                result.ManifestFiles++;
                string localRel = $"Files/{fileName}";
                if (File.Exists(Path.Combine(teaseDir, "Files", fileName)))
                {
                    map.Files[fileName] = new MapFile
                    {
                        Id = fNode["id"]?.GetValue<long>() ?? 0,
                        Hash = (fNode["hash"]?.GetValue<string>() ?? string.Empty).ToLowerInvariant(),
                        Size = fNode["size"]?.GetValue<long>() ?? 0,
                        Type = fNode["type"]?.GetValue<string>(),
                        LocalPath = localRel,
                        Locator = $"file:{fileName}",
                    };
                }
                else
                {
                    result.UnmatchedFiles.Add($"{fileName} - no local Files/ entry");
                }
            }
        }

        // ---- write asset-map.json (always; it is fully derived so this is deterministic) ----
        string mapPath = Path.Combine(teaseDir, "asset-map.json");
        File.WriteAllText(mapPath, JsonSerializer.Serialize(map, WriteOptions) + "\n");
        result.MapPath = mapPath;

        // ---- seed asset-content.json stubs for any newly-mapped images ----
        SeedContentStubs(teaseDir, teaseName, map, seededOrientation, result);

        return result;
    }

    /// <summary>Read each local jpg/png once: compute its SHA-1 and true pixel dimensions.</summary>
    private static Dictionary<string, LocalImage> IndexLocalImages(string folderAbs)
    {
        var index = new Dictionary<string, LocalImage>();
        if (!Directory.Exists(folderAbs)) return index;

        foreach (string path in Directory.EnumerateFiles(folderAbs))
        {
            string ext = Path.GetExtension(path).ToLowerInvariant();
            if (ext is not (".jpg" or ".jpeg" or ".png")) continue;

            byte[] bytes = File.ReadAllBytes(path);
            string hash = Convert.ToHexString(SHA1.HashData(bytes)).ToLowerInvariant();
            (int w, int h) = ReadDimensions(bytes);
            // Last writer wins on a hash collision (byte-identical duplicates); the manifest can only
            // reference one anyway, and either local copy resolves to the same content.
            index[hash] = new LocalImage(path, Path.GetFileName(path), w, h);
        }
        return index;
    }

    /// <summary>True pixel size from the encoded bytes; 0×0 if the image can't be decoded.</summary>
    private static (int Width, int Height) ReadDimensions(byte[] bytes)
    {
        try
        {
            using var ms = new MemoryStream(bytes);
            // OnLoad decodes now so the MemoryStream can be disposed immediately (no retained handle).
            BitmapFrame frame = BitmapFrame.Create(ms, BitmapCreateOptions.None, BitmapCacheOption.OnLoad);
            return (frame.PixelWidth, frame.PixelHeight);
        }
        catch
        {
            return (0, 0);
        }
    }

    /// <summary>
    /// Add an empty tag stub to <c>asset-content.json</c> for every mapped image it doesn't already
    /// contain, prefilling <c>orientation</c> from the known dimensions. Existing (hand-verified)
    /// entries are left untouched, and the file is written only when something was actually added —
    /// so re-running step 6 seeds nothing and stays idempotent.
    /// </summary>
    private static void SeedContentStubs(
        string teaseDir, string teaseName, AssetMap map,
        Dictionary<(string Gallery, string File), string> orientation, GenerateResult result)
    {
        string contentPath = Path.Combine(teaseDir, "asset-content.json");
        bool existed = File.Exists(contentPath);

        AssetContent content;
        if (existed)
        {
            content = JsonSerializer.Deserialize<AssetContent>(File.ReadAllText(contentPath), ReadOptions)
                      ?? new AssetContent();
        }
        else
        {
            content = new AssetContent
            {
                Tease = teaseName,
                Description = ContentDescription,
                Vocabulary = JsonNode.Parse(ContentVocabularyJson),
            };
        }

        foreach ((string galleryName, MapGallery mapGallery) in map.Galleries)
        {
            if (!content.Galleries.TryGetValue(galleryName, out GalleryTags? gallery))
            {
                gallery = new GalleryTags { Theme = "", ThemeNote = "" };
                content.Galleries[galleryName] = gallery;
            }

            foreach (string fileName in mapGallery.Images.Keys)
            {
                if (gallery.Images.ContainsKey(fileName)) continue;
                gallery.Images[fileName] = new ImageTags
                {
                    Subject = "",
                    Pace = 0,
                    Explicitness = "",
                    Orientation = orientation.GetValueOrDefault((galleryName, fileName), ""),
                    Notes = "",
                };
                result.SeededContentKeys.Add($"{galleryName}/{fileName}");
            }
        }

        // Create the file even with zero stubs the first time (gives the user a scaffold to fill in);
        // for an existing file, only rewrite when stubs were added so a no-op run touches nothing.
        if (!existed || result.SeededContentKeys.Count > 0)
        {
            File.WriteAllText(contentPath, JsonSerializer.Serialize(content, WriteOptions) + "\n");
            result.ContentWritten = true;
        }
    }

    /// <summary>Plain-text run report (mirrors the old Generate-AssetMap.ps1 output).</summary>
    public static string FormatReport(GenerateResult r)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"Tease            : {r.Tease}");
        sb.AppendLine($"Galleries        : {r.GalleriesCount}");
        sb.AppendLine($"Manifest images  : {r.ManifestImages}  | matched: {r.MatchedImages}  | unmatched: {r.UnmatchedImages.Count}");
        sb.AppendLine($"Manifest files   : {r.ManifestFiles} | unmatched: {r.UnmatchedFiles.Count}");
        sb.AppendLine($"Content stubs    : {r.SeededContentKeys.Count} seeded{(r.ContentWritten ? "" : " (asset-content.json unchanged)")}");

        if (r.UnmatchedImages.Count > 0)
        {
            sb.AppendLine("\nUNMATCHED IMAGES:");
            foreach (string s in r.UnmatchedImages) sb.AppendLine($"  {s}");
        }
        if (r.UnusedLocalFiles.Count > 0)
        {
            sb.AppendLine("\nLOCAL FILES NOT IN MANIFEST:");
            foreach (string s in r.UnusedLocalFiles) sb.AppendLine($"  {s}");
        }
        if (r.UnmatchedFiles.Count > 0)
        {
            sb.AppendLine("\nUNMATCHED FILES:");
            foreach (string s in r.UnmatchedFiles) sb.AppendLine($"  {s}");
        }
        if (r.SeededContentKeys.Count > 0)
        {
            sb.AppendLine("\nSEEDED CONTENT STUBS (need vision tagging):");
            foreach (string s in r.SeededContentKeys) sb.AppendLine($"  {s}");
        }

        sb.AppendLine(r.Ok
            ? "\nResult: OK - every manifest entry resolved"
            : "\nResult: INCOMPLETE - see unmatched above");
        sb.Append($"Wrote {r.MapPath}");
        return sb.ToString();
    }

    private sealed record LocalImage(string Path, string FileName, int Width, int Height);
}

// ---- asset-map.json DTOs (property declaration order == serialized key order) ----

internal sealed class AssetMap
{
    public string Tease { get; set; } = "";
    public string Description { get; set; } = "";
    public string HashAlgorithm { get; set; } = "sha1";
    public Dictionary<string, MapGallery> Galleries { get; set; } = new();
    public Dictionary<string, MapFile> Files { get; set; } = new();
}

internal sealed class MapGallery
{
    public string Uuid { get; set; } = "";
    public string LocalFolder { get; set; } = "";
    public Dictionary<string, MapImage> Images { get; set; } = new();
}

internal sealed class MapImage
{
    public long Id { get; set; }
    public string Hash { get; set; } = "";
    public long Size { get; set; }
    public int Width { get; set; }
    public int Height { get; set; }
    public string Locator { get; set; } = "";
}

internal sealed class MapFile
{
    public long Id { get; set; }
    public string Hash { get; set; } = "";
    public long Size { get; set; }
    public string? Type { get; set; }
    public string LocalPath { get; set; } = "";
    public string Locator { get; set; } = "";
}

/// <summary>Outcome of one <see cref="AssetMapGenerator.Run"/>, for the CLI report and UI summary.</summary>
internal sealed class GenerateResult
{
    public string Tease { get; set; } = "";
    public string MapPath { get; set; } = "";
    public int GalleriesCount { get; set; }
    public int ManifestImages { get; set; }
    public int MatchedImages { get; set; }
    public int ManifestFiles { get; set; }
    public List<string> UnmatchedImages { get; } = new();
    public List<string> UnusedLocalFiles { get; } = new();
    public List<string> UnmatchedFiles { get; } = new();
    public List<string> SeededContentKeys { get; } = new();
    public bool ContentWritten { get; set; }

    /// <summary>True when every manifest image and file resolved to a local source.</summary>
    public bool Ok => UnmatchedImages.Count == 0 && UnmatchedFiles.Count == 0;
}
